# Generated by Django 4.1 on 2022-08-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_alter_despesa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(blank=True, choices=[('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevisto'), ('O', 'Outras')], default='O', max_length=1, null=True),
        ),
    ]
