# Generated by Django 4.1 on 2022-08-15 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas', '0006_alter_despesa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financas', to=settings.AUTH_USER_MODEL),
        ),
    ]
